### ISSUE TITLE
unable to export urls to TikTokContent.bat and download to computer

### ISSUE THREAD

**Issue by HungNth01** [Dinoosauro/TikTok-video-downloader#1]

**Comment by Dinoosauro** [comment]
Hi! Is the problem on the execution of the .bat file or is on the creation of the file?
If it's in the creation of the script, can you provide the link of the profile you are trying to download the videos? And are you using TikTok's light mode or dark mode?
If it's on the execution of the .bat/.sh file, which error does the terminal output?
Let me know if there are any other issues

**Comment by HungNth01** [comment]
Hello,
Sorry, it's my fault, I use it on another computer and it still works

**Comment by Dinoosauro** [comment]
Don't worry. If you encounter into any other issue, feel free to ask
