### ISSUE TITLE
Continue downloading only the first video

### ISSUE THREAD

**Issue by moseoridev** [Dinoosauro/TikTok-video-downloader#2]
It continues to download only the first video (downloads first video multiple times)
The yt-dlp option works well, so there seems to be a minor error in the download script.
Can you fix the bug, please?

**Comment by Dinoosauro** [comment]
Yes that download option is broken. I'm working on a fix with a new method, I just need to solve a few issues before publishing it. I should be able to publish it tomorrow (in Central European time)

**Comment by moseoridev** [comment]
Ok thank you very much :)
